### ISSUE TITLE
Fix encodings::encoding::tests::test_byte_array

### ISSUE THREAD

**Issue by sunchao** [sunchao/parquet-rs#47]
Seems this test is flaky.

<img width="1089" alt="screen shot 2018-02-19 at 9 50 05 pm" src="https://user-images.githubusercontent.com/506679/36409201-0539edd8-15bf-11e8-9e98-8ca1ee200e16.png">

**Comment by sadikovi** [comment]
How often do you reproduce this? Could you provide some information on how to reproduce this error? I tried running all tests several times in a row, and all tests were passing.

Hopefully, it is not a bug in actual implementation!:)

**Comment by sunchao** [comment]
I can't reproduce it locally either - just saw it once in the travis job. Let's keep it open for now and see if it happens again. :)

**Comment by sadikovi** [comment]
Here is a full stack trace for the failure (commit 7eaed58dd44d0005bae3d45b8eea00e8b0835cdc):
```
failures:
---- encodings::encoding::tests::test_byte_array stdout ----
thread 'encodings::encoding::tests::test_byte_array' panicked at 'index 1 out of range for slice of length 0', libcore/slice/mod.rs:1971:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:221
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::slice::slice_index_len_fail
             at libcore/slice/mod.rs:1971
   9: <core::ops::range::Range<usize> as core::slice::SliceIndex<[T]>>::index
             at /checkout/src/libcore/slice/mod.rs:2136
  10: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /checkout/src/libcore/slice/mod.rs:1953
  11: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /checkout/src/liballoc/vec.rs:1714
  12: <parquet::encodings::decoding::DeltaByteArrayDecoder<parquet::data_type::ByteArrayType> as parquet::encodings::decoding::Decoder<parquet::data_type::ByteArrayType>>::get
             at src/encodings/decoding.rs:835
  13: <T as parquet::encodings::encoding::tests::EncodingTester<T>>::test_internal
             at src/encodings/encoding.rs:1195
  14: parquet::encodings::encoding::tests::EncodingTester::test
             at src/encodings/encoding.rs:1158
  15: parquet::encodings::encoding::tests::test_byte_array
             at src/encodings/encoding.rs:1052
  16: parquet::__test::TESTS::{{closure}}
             at src/encodings/encoding.rs:1048
  17: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  18: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1454
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:640
  19: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:106
```

**Comment by sunchao** [comment]
Thanks @sadikovi . I filed a PR to fix this issue.
